package lp2.juegolp2.Interfaz;

import java.awt.*;
import java.awt.image.BufferedImage;
import javax.swing.JOptionPane;

/**
 *
 * @author pmvb
 */
public class Map extends javax.swing.JPanel
{
    private GameWindow parent;
    
    /**
     * Creates new form Map
     */
    public Map(int width, int height, GameWindow parent)
    {
        initComponents();
        
        this.setPreferredSize(new Dimension(width, height));
        this.setBounds(new Rectangle(0, 0, width, height));
        this.setFocusable(true);
        this.parent = parent;
    }

    @Override
    public void paintComponent(Graphics g)
    {
        super.paintComponent(g);
        
        BufferedImage img = this.parent.getDibujador().getImageLoader().getImage("back1");
        try {
            img = null;
            Image tmp = img.getScaledInstance(this.getWidth(), this.getHeight(), Image.SCALE_SMOOTH);
            BufferedImage back = new BufferedImage(this.getWidth(), this.getHeight(), BufferedImage.TYPE_INT_ARGB);
            Graphics g2 = back.createGraphics();
            g2.drawImage(tmp, 0, 0, null);
            g2.dispose();
            
            g.drawImage(back, 0, 0, null);
            this.parent.getDibujador().dibujarLaberinto(g);
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(parent, "No se pudo cargar las imagenes", "Error", JOptionPane.ERROR_MESSAGE);
            parent.getDibujador().endGame();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
