package lp2.juegolp2.Interfaz;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author pmvb
 */
public class Sidebar extends javax.swing.JPanel
{

    /**
     * Creates new form Sidebar
     */
    public Sidebar(int width, int height) {
        initComponents();
        this.setPreferredSize(new Dimension(width, height));
        this.playerInfoArea.setEditable(false);
        this.BattleTextArea.setEditable(false);
        this.hideBattleArea();
        this.hideCommandArea();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        playerInfoArea = new javax.swing.JTextArea();
        playerLabel = new javax.swing.JLabel();
        commandTextField = new javax.swing.JTextField();
        commandLabel = new javax.swing.JLabel();
        commandButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        BattleTextArea = new javax.swing.JTextArea();
        battleLabel = new javax.swing.JLabel();

        playerInfoArea.setColumns(20);
        playerInfoArea.setRows(5);
        jScrollPane1.setViewportView(playerInfoArea);

        playerLabel.setText("Jugador:");

        commandLabel.setText("Comando:");

        commandButton.setText("Actuar");
        commandButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                commandButtonMouseClicked(evt);
            }
        });

        BattleTextArea.setColumns(20);
        BattleTextArea.setRows(5);
        jScrollPane2.setViewportView(BattleTextArea);

        battleLabel.setText("Batalla:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(commandTextField)
                        .addGap(26, 26, 26)
                        .addComponent(commandButton)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(playerLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(commandLabel, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(battleLabel)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(playerLabel)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(commandLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(commandTextField)
                    .addComponent(commandButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(battleLabel)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void commandButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_commandButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_commandButtonMouseClicked
    
    public void setPlayerInfo(String info)
    {
        this.playerInfoArea.setText(info);
    }
    
    public void setBattleInterface(String data)
    {
        this.BattleTextArea.setText(data);
    }
    
    public void hideBattleArea()
    {
        this.jScrollPane2.setVisible(false);
        this.battleLabel.setVisible(false);
        this.BattleTextArea.setVisible(false);
    }
    
    public void showBattleArea()
    {
        this.jScrollPane2.setVisible(true);
        this.BattleTextArea.setVisible(true);
        this.battleLabel.setVisible(true);
    }
    
    private void hideCommandArea()
    {
        this.commandButton.setVisible(false);
        this.commandLabel.setVisible(false);
        this.commandTextField.setVisible(false);
    }
    
    private void showCommandArea()
    {
        this.commandButton.setVisible(true);
        this.commandLabel.setVisible(true);
        this.commandTextField.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea BattleTextArea;
    private javax.swing.JLabel battleLabel;
    private javax.swing.JButton commandButton;
    private javax.swing.JLabel commandLabel;
    private javax.swing.JTextField commandTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea playerInfoArea;
    private javax.swing.JLabel playerLabel;
    // End of variables declaration//GEN-END:variables
}
