package lp2.juegolp2.Interfaz;

import java.awt.*;
import java.awt.event.KeyEvent;
import javax.swing.*;

/**
 *
 * @author pmvb
 */
public class Sidebar extends javax.swing.JPanel
{
    private GameWindow parent;
    /**
     * Creates new form Sidebar
     */
    public Sidebar(int width, int height, GameWindow parent) {
        initComponents();
        this.parent = parent;
        this.setPreferredSize(new Dimension(width, height));
        
        init();
    }

    private void init()
    {
        this.jScrollPane1.setBorder(BorderFactory.createEmptyBorder());
        this.playerInfoArea.setEditable(false);
        this.playerInfoArea.setOpaque(false);
        //this.playerInfoArea.setBorder(BorderFactory.createEmptyBorder());
        
        this.jScrollPane2.setBorder(BorderFactory.createEmptyBorder());
        this.BattleTextArea.setEditable(false);
        this.BattleTextArea.setOpaque(false);
        //this.BattleTextArea.setBorder(BorderFactory.createEmptyBorder());
        
        this.hideBattleArea();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        playerInfoArea = new javax.swing.JTextArea();
        playerLabel = new javax.swing.JLabel();
        quitBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        BattleTextArea = new javax.swing.JTextArea();
        battleLabel = new javax.swing.JLabel();
        interactBtn = new javax.swing.JButton();
        useItemBtn = new javax.swing.JButton();

        playerInfoArea.setColumns(20);
        playerInfoArea.setRows(5);
        jScrollPane1.setViewportView(playerInfoArea);

        playerLabel.setText("Jugador:");

        quitBtn.setText("Salir");
        quitBtn.setPreferredSize(new java.awt.Dimension(80, 31));
        quitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quitBtnMouseClicked(evt);
            }
        });
        quitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitBtnActionPerformed(evt);
            }
        });

        BattleTextArea.setColumns(20);
        BattleTextArea.setRows(5);
        jScrollPane2.setViewportView(BattleTextArea);

        battleLabel.setText("Batalla:");

        interactBtn.setText("Interactuar");
        interactBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                interactBtnMouseClicked(evt);
            }
        });

        useItemBtn.setText("Usar");
        useItemBtn.setPreferredSize(new java.awt.Dimension(80, 31));
        useItemBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                useItemBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(battleLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(playerLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(interactBtn)
                                        .addGap(18, 18, 18)
                                        .addComponent(useItemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(quitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(playerLabel)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(interactBtn)
                    .addComponent(quitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(useItemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(battleLabel)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void useItemBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_useItemBtnMouseClicked
        this.parent.useItemAction();
    }//GEN-LAST:event_useItemBtnMouseClicked

    private void quitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitBtnActionPerformed
        this.parent.quitGameAction();
    }//GEN-LAST:event_quitBtnActionPerformed

    private void quitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quitBtnMouseClicked
        this.parent.quitGameAction();
    }//GEN-LAST:event_quitBtnMouseClicked

    private void interactBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_interactBtnMouseClicked
        this.parent.interactAction();
    }//GEN-LAST:event_interactBtnMouseClicked
    
    @Override
    public void paintComponent(Graphics g)
    {
        super.paintComponent(g);
        
        String info = this.parent.getDibujador().getPlayerInfo();
        this.setPlayerInfo(info);
    }
    
    public void setPlayerInfo(String info)
    {
        this.playerInfoArea.setText(info);
    }
    
    public void setBattleInterface(String data)
    {
        this.BattleTextArea.setText(data);
    }
    
    public void hideBattleArea()
    {
        this.jScrollPane2.setVisible(false);
        this.battleLabel.setVisible(false);
        this.BattleTextArea.setVisible(false);
    }
    
    public void showBattleArea()
    {
        this.jScrollPane2.setVisible(true);
        this.BattleTextArea.setVisible(true);
        this.battleLabel.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea BattleTextArea;
    private javax.swing.JLabel battleLabel;
    private javax.swing.JButton interactBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea playerInfoArea;
    private javax.swing.JLabel playerLabel;
    private javax.swing.JButton quitBtn;
    private javax.swing.JButton useItemBtn;
    // End of variables declaration//GEN-END:variables
}
